"""
Shared helpers for the nanoSE homework notebooks.

The notebooks drive the *unmodified* command line workflow of the repository
(``python train.py --config ...`` / ``python create_report.py ...``); everything
in here is glue: writing config files, launching training as a subprocess while
streaming its output into the notebook, and reading the logs back for analysis.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Repository / environment
# ---------------------------------------------------------------------------

_REPO_MARKERS = ("train.py", "create_report.py", "models")


def in_colab() -> bool:
    return "google.colab" in sys.modules


def find_repo_root(start: str | os.PathLike | None = None) -> Path:
    """Walks upwards from `start` (or the cwd) until the nanoSE root is found."""
    here = Path(start or os.getcwd()).resolve()
    for candidate in (here, *here.parents):
        if all((candidate / marker).exists() for marker in _REPO_MARKERS):
            return candidate
    raise RuntimeError(
        f"Could not locate the nanoSE repository root starting from {here}. "
        "Run the notebook from inside a clone of the repository."
    )


def bootstrap(verbose: bool = True) -> Path:
    """
    Makes the notebook behave like a shell sitting in the repository root:
    changes the working directory there and puts it on ``sys.path``.
    Returns the repository root.
    """
    root = find_repo_root()
    os.chdir(root)
    if str(root) not in sys.path:
        sys.path.insert(0, str(root))
    if verbose:
        print(f"Repository root: {root}")
        print(describe_device())
        _warn_if_unpatched()
    return root


def describe_device() -> str:
    import torch

    if torch.cuda.is_available():
        name = torch.cuda.get_device_name(0)
        mem = torch.cuda.get_device_properties(0).total_memory / 1e9
        return f"torch {torch.__version__} | CUDA GPU: {name} ({mem:.1f} GB)"
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        return f"torch {torch.__version__} | Apple MPS GPU"
    return (
        f"torch {torch.__version__} | CPU only ({torch.get_num_threads()} threads) "
        "-- full-scale training will be very slow, use a GPU runtime"
    )


def _warn_if_unpatched() -> None:
    """The notebooks need the homework modifications to models/crn.py."""
    try:
        from models.crn import get_activation  # noqa: F401
    except ImportError:
        print(
            "WARNING: models/crn.py does not expose get_activation(). This clone is "
            "the upstream version; the activation / loss experiments will not run. "
            "Clone the fork that contains the homework modifications."
        )


# ---------------------------------------------------------------------------
# Config files
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = '''"""{docstring}

Generated by the nanoSE homework notebooks -- edit the notebook, not this file.
"""

{imports}

# Log folder identifier name
name = "{name}"

# Training settings
{settings}

# Model definition
model = {model}
'''

_DEFAULTS = dict(
    epochs=25,
    batch_size=32,
    lr=1e-3,
    wd=0.02,
    compile=False,
    seed=42,
    remix=False,
)


def write_config(
    filename: str,
    *,
    name: str,
    model: str = "CRNTiny()",
    imports: str = "from models.crn import CRNTiny",
    docstring: str = "nanoSE experiment configuration.",
    directory: str = "config",
    **overrides,
) -> Path:
    """
    Writes a ``config/*.py`` file in the exact style of ``config/default_config.py``.

    `model` is written verbatim as a Python expression, so
    ``write_config(..., model='CRNTiny(activation="prelu")')`` is the way to
    configure the model itself. Unknown keyword arguments become extra config
    variables (e.g. ``warmup_steps=100``).
    """
    settings = dict(_DEFAULTS)
    settings.update(overrides)

    lines = []
    for key, value in settings.items():
        lines.append(f"{key} = {value!r}")

    path = Path(directory) / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        _CONFIG_TEMPLATE.format(
            docstring=docstring,
            imports=imports,
            name=name,
            settings="\n".join(lines),
            model=model,
        ),
        encoding="utf-8",
    )
    return path


# ---------------------------------------------------------------------------
# Running training
# ---------------------------------------------------------------------------

_RUN_DIR_RE = re.compile(r"Copied config file to log folder:\s*(\S+)/config\.py")
_EPOCH_RE = re.compile(
    r"Epoch\s+(?P<epoch>\d+)/(?P<total>\d+)\s*\|\s*"
    r"Loss:\s*(?P<loss>[-\d.eE+]+).*?"
    r"Train SI-SDR:\s*(?P<train_si_sdr>[-\d.]+)dB\s*\|\s*"
    r"Val SI-SDR:\s*(?P<val_si_sdr>[-\d.]+)dB\s*\|\s*"
    r"PESQ:\s*(?P<pesq>[-\d.]+)\s*\|\s*STOI:\s*(?P<estoi>[-\d.]+)\s*\|\s*"
    r"DNSMOS:\s*(?P<dnsmos>[-\d.]+)\s*\|\s*Time:\s*(?P<time>[-\d.]+)s"
)


def parse_train_log(text: str) -> list[dict]:
    """Extracts one record per finished epoch from captured training output."""
    records = []
    for match in _EPOCH_RE.finditer(text):
        record = {k: float(v) for k, v in match.groupdict().items()}
        record["epoch"] = int(record["epoch"])
        record["total"] = int(record["total"])
        records.append(record)
    return records


def _stream_output(process, echo: bool = True, width: int = 160) -> str:
    """
    Reads the child process output, splitting on both newlines and carriage
    returns so tqdm progress bars refresh in place instead of flooding the cell.
    """
    chunks: list[str] = []
    buffer = ""
    while True:
        data = process.stdout.read(256)
        if not data:
            break
        chunks.append(data)
        buffer += data
        while True:
            match = re.search(r"[\r\n]", buffer)
            if match is None:
                break
            line, buffer = buffer[: match.start()], buffer[match.end() :]
            if not echo or not line.strip():
                continue
            if match.group(0) == "\n":
                print(line, flush=True)
            else:  # progress bar refresh
                print("\r" + line[:width].ljust(width), end="", flush=True)
    if buffer.strip():
        chunks.append("\n")
        if echo:
            print(buffer, flush=True)
    return "".join(chunks)


def run_training(
    config_path: str | os.PathLike,
    extra_args: tuple | list = (),
    echo: bool = True,
    progress_bars: bool = True,
) -> Path:
    """
    Runs ``python train.py --config <config_path>`` and returns the run directory.

    Alongside the artifacts written by ``train.py`` the run directory also gets
    ``train_log.txt`` (full captured output), ``progress.json`` (per-epoch
    metrics *and wall-clock time*, used by the speed analysis) and
    ``timing.json`` (total wall time).
    """
    config_path = Path(config_path)
    cmd = [sys.executable, "train.py", "--config", str(config_path), *map(str, extra_args)]
    print("$ " + " ".join(cmd[1:]))

    env = dict(os.environ, PYTHONUNBUFFERED="1")
    if not progress_bars:
        env["TQDM_DISABLE"] = "1"

    started = time.time()
    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    output = _stream_output(process, echo=echo)
    process.wait()
    elapsed = time.time() - started

    if process.returncode != 0:
        raise RuntimeError(
            f"Training failed with exit code {process.returncode}. "
            "The captured output is printed above."
        )

    match = _RUN_DIR_RE.search(output)
    if match is None:
        raise RuntimeError("Could not determine the run directory from the output.")
    run_dir = Path(match.group(1))

    (run_dir / "train_log.txt").write_text(output, encoding="utf-8")
    records = parse_train_log(output)
    (run_dir / "progress.json").write_text(json.dumps(records, indent=2), encoding="utf-8")
    (run_dir / "timing.json").write_text(
        json.dumps({"total_wall_time_s": elapsed, "config": str(config_path)}, indent=2),
        encoding="utf-8",
    )
    print(f"\nRun directory: {run_dir}  (total wall time {elapsed / 60:.1f} min)")
    return run_dir


def create_report(run_dirs, output: str = "report/report.md", best_epoch: bool = True) -> str:
    """Calls ``create_report.py`` on the given run directories, returns the markdown."""
    cmd = [sys.executable, "create_report.py", "--output", str(output)]
    if best_epoch:
        cmd.append("--best-epoch")
    cmd += [str(d) for d in run_dirs]
    subprocess.run(cmd, check=True, capture_output=True, text=True)
    return Path(output).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Reading results back
# ---------------------------------------------------------------------------


def load_metrics(run_dir: str | os.PathLike):
    """
    Returns a DataFrame of the per-epoch validation metrics of one run, with the
    cumulative wall-clock time joined in when ``progress.json`` is available.
    """
    import pandas as pd

    run_dir = Path(run_dir)
    path = run_dir / "validation_metrics.jsonl"
    if not path.exists():
        return pd.DataFrame()
    records = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]
    frame = pd.DataFrame(records)

    progress_path = run_dir / "progress.json"
    if progress_path.exists():
        progress = pd.DataFrame(json.loads(progress_path.read_text(encoding="utf-8")))
        if not progress.empty:
            progress = progress[["epoch", "loss", "train_si_sdr", "time"]]
            frame = frame.merge(progress, on="epoch", how="left")
            frame["time"] = frame["time"].fillna(0.0)
            frame["cumulative_time_min"] = frame["time"].cumsum() / 60.0
    frame["run"] = run_dir.name
    return frame


def load_config(run_dir: str | os.PathLike) -> dict:
    """Reads back the archived ``config.py`` of a run as a plain dict."""
    from models.crn import CRN, CRNTiny  # noqa: F401

    path = Path(run_dir) / "config.py"
    if not path.exists():
        return {}
    namespace: dict = {}
    exec(compile(path.read_text(encoding="utf-8"), str(path), "exec"), namespace, namespace)
    return {k: v for k, v in namespace.items() if not k.startswith("__")}


def summarize(run_dirs, labels=None, best_epoch: bool = True):
    """One row per run: the best (or last) epoch plus the key hyperparameters."""
    import pandas as pd

    rows = []
    for index, run_dir in enumerate(run_dirs):
        run_dir = Path(run_dir)
        frame = load_metrics(run_dir)
        config = load_config(run_dir)
        if frame.empty:
            continue
        trained = frame[frame["epoch"] > 0]
        if trained.empty:
            trained = frame
        selected = (
            trained.loc[trained["val_si_sdr"].idxmax()] if best_epoch else trained.iloc[-1]
        )
        model = config.get("model")
        row = {
            "label": labels[index] if labels else run_dir.name,
            "model": type(model).__name__ if model is not None else "N/A",
            "activation": getattr(model, "activation_name", "leaky_relu"),
            "lr": config.get("lr"),
            "batch_size": config.get("batch_size"),
            "epochs": config.get("epochs"),
            "remix": config.get("remix"),
            "epoch": int(selected["epoch"]),
            "val_si_sdr": selected["val_si_sdr"],
            "pesq": selected["pesq"],
            "estoi": selected["estoi"],
            "dnsmos": selected["dnsmos"],
        }
        if "cumulative_time_min" in selected:
            row["time_min"] = selected["cumulative_time_min"]
        rows.append(row)
    return pd.DataFrame(rows).sort_values("val_si_sdr", ascending=False).reset_index(drop=True)


def time_to_reach(run_dir, target_si_sdr: float):
    """Minutes of training needed to first reach `target_si_sdr` (NaN if never)."""
    frame = load_metrics(run_dir)
    if frame.empty or "cumulative_time_min" not in frame:
        return float("nan")
    reached = frame[(frame["epoch"] > 0) & (frame["val_si_sdr"] >= target_si_sdr)]
    return float(reached["cumulative_time_min"].iloc[0]) if not reached.empty else float("nan")


REGISTRY_PATH = Path("notebooks/experiment_runs.json")


def registry() -> dict:
    """The run directories recorded by the notebooks so far, keyed by short name."""
    if REGISTRY_PATH.exists():
        return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    return {}


def remember(key: str, run_dir) -> Path:
    """Records a run directory so that later notebooks can pick it up."""
    entries = registry()
    entries[key] = str(run_dir).replace("\\", "/")
    REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_PATH.write_text(json.dumps(entries, indent=2, sort_keys=True), encoding="utf-8")
    return Path(entries[key])


def recall(key: str, default=None):
    """Looks up a run directory recorded with `remember`; falls back to `default`."""
    entry = registry().get(key)
    if entry is None:
        return default
    path = Path(entry)
    return path if path.exists() else default


def find_runs(pattern: str = "*", runs_dir: str = "runs"):
    """Run directories that contain metrics, newest last."""
    candidates = sorted(Path(runs_dir).glob(pattern))
    return [p for p in candidates if (p / "validation_metrics.jsonl").exists()]


def latest_run(name: str, runs_dir: str = "runs"):
    """The most recent run directory whose config `name` matches, or None."""
    matches = find_runs(f"*{name}*", runs_dir)
    return matches[-1] if matches else None


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

# Fixed categorical order -- assigned by series identity, never cycled.
PALETTE = [
    "#2a78d6",  # blue
    "#eb6834",  # orange
    "#1baf7a",  # aqua
    "#eda100",  # yellow
    "#e87ba4",  # magenta
    "#008300",  # green
    "#4a3aa7",  # violet
    "#e34948",  # red
]
GRID = "#dcdcd8"
INK = "#0b0b0b"
INK_SOFT = "#52514e"


def style_axes(ax, title: str = "", xlabel: str = "", ylabel: str = ""):
    """Recessive grid and axes, text in ink tokens rather than series colors."""
    ax.set_title(title, color=INK, fontsize=12, loc="left", pad=10)
    ax.set_xlabel(xlabel, color=INK_SOFT, fontsize=10)
    ax.set_ylabel(ylabel, color=INK_SOFT, fontsize=10)
    ax.grid(True, color=GRID, linewidth=0.8, alpha=0.9)
    ax.set_axisbelow(True)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(GRID)
    ax.tick_params(colors=INK_SOFT, labelsize=9)
    return ax


def plot_curves(
    run_dirs,
    labels=None,
    metric: str = "val_si_sdr",
    x: str = "epoch",
    title: str | None = None,
    ylabel: str | None = None,
    ax=None,
):
    """
    Overlays one line per run. Series colors follow the run's position in the
    fixed palette; a legend is always drawn when more than one run is shown.
    """
    import matplotlib.pyplot as plt

    labels = list(labels) if labels else [Path(d).name for d in run_dirs]
    if len(run_dirs) > len(PALETTE):
        raise ValueError(
            f"{len(run_dirs)} runs exceeds the {len(PALETTE)}-slot categorical palette; "
            "split the comparison into small multiples instead."
        )
    if ax is None:
        _, ax = plt.subplots(figsize=(8, 4.5))

    for index, (run_dir, label) in enumerate(zip(run_dirs, labels)):
        frame = load_metrics(run_dir)
        if frame.empty or metric not in frame:
            continue
        color = PALETTE[index]
        ax.plot(
            frame[x],
            frame[metric],
            color=color,
            linewidth=2,
            marker="o",
            markersize=4.5,
            label=label,
        )
        # Direct label on the final point (identity is never color-alone)
        if len(run_dirs) <= 4 and len(frame):
            last = frame.iloc[-1]
            ax.annotate(
                label,
                (last[x], last[metric]),
                textcoords="offset points",
                xytext=(6, 0),
                color=INK_SOFT,
                fontsize=9,
                va="center",
            )

    pretty = {
        "val_si_sdr": "Validation SI-SDR (dB)",
        "pesq": "PESQ",
        "estoi": "eSTOI",
        "dnsmos": "DNSMOS (OVRL)",
        "loss": "Training loss",
        "train_si_sdr": "Training SI-SDR (dB)",
    }
    xpretty = {"epoch": "Epoch", "cumulative_time_min": "Wall-clock training time (min)"}
    style_axes(
        ax,
        title=title or pretty.get(metric, metric),
        xlabel=xpretty.get(x, x),
        ylabel=ylabel or pretty.get(metric, metric),
    )
    if len(run_dirs) > 1:
        ax.legend(frameon=False, fontsize=9, labelcolor=INK_SOFT)
    return ax


def plot_bars(labels, values, title: str = "", ylabel: str = "", baseline=None, ax=None):
    """Ranked horizontal bars -- the form for comparing a magnitude across runs."""
    import matplotlib.pyplot as plt

    if ax is None:
        _, ax = plt.subplots(figsize=(8, 0.45 * len(labels) + 1.8))
    order = sorted(range(len(values)), key=lambda i: values[i])
    labels = [labels[i] for i in order]
    values = [values[i] for i in order]

    ax.barh(labels, values, color=PALETTE[0], height=0.62)
    if baseline is not None:
        ax.axvline(baseline, color=INK_SOFT, linewidth=1.2, linestyle="--")
        ax.annotate(
            "baseline",
            (baseline, len(labels) - 0.4),
            color=INK_SOFT,
            fontsize=9,
            xytext=(4, 0),
            textcoords="offset points",
        )
    for index, value in enumerate(values):
        ax.annotate(
            f"{value:.2f}",
            (value, index),
            xytext=(4, 0),
            textcoords="offset points",
            va="center",
            color=INK_SOFT,
            fontsize=9,
        )
    style_axes(ax, title=title, xlabel=ylabel)
    ax.grid(axis="y", visible=False)
    ax.margins(x=0.12)
    return ax
